version: "3.9"
services:
  minio:
    container_name: minio
    hostname: minio
    image: minio/minio:RELEASE.2024-03-15T01-07-19Z
    privileged: true
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: "no"
    environment:
      TZ: "Asia/Shanghai"
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "wvOszZh5"
    volumes:
      - .env/minio/data:/data